/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2014 VigLink. Rights reserved and patent(s) pending.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(l){var g,b={_breaker:{},each:function(a,c){var d,e;if("object"===b.type(a)&&a.hasOwnProperty)for(d in a){if(a.hasOwnProperty(d)&&c(a[d],d)===b._breaker)break}else if(a){d=0;for(e=a.length;d<e&&c(a[d],d)!==b._breaker;d++);}},extend:function(a){var c,d,b,f,h=arguments.length;a=a||{};for(d=1;d<h;d++)if(f=arguments[d],void 0!==f&&null!==f)for(b in f)c=f[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(a,d){try{return("function"===typeof window[d]||"object"===
typeof window[d])&&a instanceof window[d]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},
attrValues:function(a,c,d){return(c=a[c])?c.split(d||" "):[]},batchable:function(a){a=b.extend({batch:b.noop,single:b.noop,timeout:100},a);var c=[],d=b.traits.cors&&b.traits.json,e=null,f=function(){null!==e&&(clearTimeout(e),e=null);1===c.length?a.single.apply(this,c[0]):1<c.length&&a.batch(c);c=[]},h=function(){c.push(b.toArray(arguments));d?null===e&&(e=setTimeout(b.bind(function(){f()},this),a.timeout)):f()};b.extend(h,{flush:f,now:a.single});return h},bind:function(a,c){return function(){return a.apply(c,
arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),d=0;return function(b,f,h){if(b){var m=b[c];if(m||void 0!==h)return m||(m=++d),a[m]||(b[c]=m,a[m]={}),void 0!==h&&(a[m][f]=h),"string"===typeof f?a[m][f]:a[m]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return b.extend({},a)},contains:function(a,c){return-1!==b.indexOf(a,c)},context:function(a){"element"===
b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,c){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,d===c)return!0;return!1},cors:function(a,c,d){var b,f=function(){d?d(b.responseText):eval(b.responseText)};b=new window.XMLHttpRequest;b.onreadystatechange=function(){4===b.readyState&&200===
b.status&&f()};try{return b.open("POST",a),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.withCredentials=!0,b.send(c),!0}catch(h){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,e){var f;a=(e||document).createElement(a);c=c||{};d=d||{};for(f in c)void 0!==c[f]&&(a[f]=c[f]);b.css(a,d);return a},css:function(a,c){for(var d in c)try{a.style[d]=c[d]}catch(b){}return a},destructing:function(a){return function(a){var b=!1,e;return function(){b||
(e=a.apply(null,arguments),b=!0);return e}}(a)},escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(e){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,e){if(void 0!==e)a=e,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(e){c(e)}else return b.apply(this,
arguments)}}}(),find:function(a,c){var d;b.each(a,function(a,f){if(c(a,f))return d=a,b._breaker});return d},generateNodeFilter:function(){var a=function(a,b){var f,h;b=","+b.join(",")+",";f=0;for(h=a.length;f<h;f++)if(c(a[f],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,f){f=b.extend({ancestors:!0,self:!0},f);var h=!0,m=
!0,g=function(e,f){var h;if(h=!(d.tags.length&&c(e.nodeName.toLowerCase(),d.tags))){if(h=d.classes.length){h=d.classes;var m=b.attrValues(e,"className");h=a(h,m)}if(h=!h){if(h=d.rels.length)h=d.rels,m=b.attrValues(e,"rel"),h=c(e.nodeName.toLowerCase(),",a,")&&a(h,m);h=!h&&!("function"===b.type(d.custom)&&d.custom(e,f))}}return h},m=!f.self||g(e,!0);if(f.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!g(e,!1)){h=!1;break}return m&&h}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},
fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,e=Infinity,f=-Infinity,h=-Infinity,m;for(a=0;a<c;a++)m=b.position(arguments[a]),d=Math.min(d,m.x),e=Math.min(e,m.y),f=Math.max(f,m.x+arguments[a].offsetWidth),h=Math.max(h,m.y+arguments[a].offsetHeight);return{x:d,y:e,w:f-d,h:h-e,x1:d,y1:e,x2:f,y2:h}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,d,e){return c?b.contains(b.attrValues(a,c,e),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},indexOf:function(){return Array.prototype.indexOf?function(a,c){return Array.prototype.indexOf.call(a,c)}:function(a,c){var b,e;b=0;for(e=a.length;b<e;b++)if(a[b]===c)return b;return-1}}(),isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&
a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c){var d=[];b.each(a,function(a,b){void 0!==a&&(d[b]=c(a))});return d},matches:function(){try{return this.Sizzle.matchesSelector.apply(this.Sizzle,arguments)}catch(a){return!0}},on:function(){var a;return function(c,d,e){var f,h;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;e=d;d=c;c=a}try{f=c["on"+d]}catch(m){}"function"===typeof f&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=f.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));h=b.exceptionLogger(function(){if(a.enabled())return e.apply(null,arguments)});c.addEventListener?c.addEventListener(d,h,!1):c.attachEvent&&
c.attachEvent("on"+d,h)}}}(),position:function(a,c){var b,e=0,f=0,h=0,m=0;c=c||document;if(!a.offsetParent)return!1;b=a;do e+=b.offsetLeft,f+=b.offsetTop,b=b.offsetParent;while(b);b=a;do h+=b.scrollLeft,m+=b.scrollTop,b=b.parentNode;while(b&&b!==c.body);return{x:e-h,y:f-m}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});return a},ready:function(){var a=!1,c=[],d=!1,e,f,h,m,g;document.addEventListener?
h=function(){document.removeEventListener("DOMContentLoaded",h,!1);g()}:document.attachEvent&&(m=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),g())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return g();if(document.addEventListener)document.addEventListener("DOMContentLoaded",h,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",m);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&
c&&f()}b.on(window,"load",g)}};f=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.exceptionLogger(f),1);return}g()}};g=function(){if(!d){if(!document.body)return setTimeout(b.exceptionLogger(g),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){e();d?a():c.push(a)}}(),reformatKeys:function(a){var c,d,e=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,e),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=
a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,e,f=b.attrValues(a,"className");d=0;for(e=f.length;d<e;d++)f[d]===c&&delete f[d];a.className=f.join(" ")}},request:function(a,c,d){var e,f;d=b.extend({fn:b.noop,jsonp:!0,"return":!1,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],f=d.fn):"function"===typeof d.fn&&(!0!==d.jsonp?e=d.fn:(e=b.destructing(d.fn),f=b.uniqid("vglnk_jsonp_"),window[f]=b.exceptionLogger(function(){e.apply(this,arguments);window[f]=void 0}),
null!==d.timeout&&setTimeout(b.exceptionLogger(e),d.timeout)));f&&(c=b.extend({format:"jsonp",jsonp:f},c));c=b.toQuery(c);return d["return"]?a+(c.length?"?":"")+c:b.traits.cors&&b.cors(a,c,d.jsonp?null:e)?!0:b.jsonp(a+(c.length?"?":"")+c)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,e,f=[];b=0;for(e=a.length;b<e;b++)f[b]=a[b];return f}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},
toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},transmitsPII:function(a){return b.containsPII(a+" "+document.referrer)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}()});var u=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};u.amd=!0;(function(a){function c(a,
b,c,d){var e,f,h,m,g;(b?b.ownerDocument||b:B)!==y&&J(b);b=b||y;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(m=b.nodeType)&&9!==m)return[];if(E&&!d){if(e=qa.exec(a))if(h=e[1])if(9===m)if((f=b.getElementById(h))&&f.parentNode){if(f.id===h)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(h))&&U(b,f)&&f.id===h)return c.push(f),c}else{if(e[2])return K.apply(c,b.getElementsByTagName(a)),c;if((h=e[3])&&v.getElementsByClassName&&b.getElementsByClassName)return K.apply(c,
b.getElementsByClassName(h)),c}if(v.qsa&&(!z||!z.test(a))){f=e=x;h=b;g=9===m&&a;if(1===m&&"object"!==b.nodeName.toLowerCase()){m=V(a);(e=b.getAttribute("id"))?f=e.replace(ra,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(h=m.length;h--;)m[h]=f+n(m[h]);h=da.test(a)&&t(b.parentNode)||b;g=m.join(",")}if(g)try{return K.apply(c,h.querySelectorAll(g)),c}catch(k){}finally{e||b.removeAttribute("id")}}}return ja(a.replace(Y,"$1"),b,c,d)}function b(){function a(b,d){c.push(b+" ")>s.cacheLength&&delete a[c.shift()];
return a[b+" "]=d}var c=[];return a}function e(a){a[x]=!0;return a}function f(a){var b=y.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function h(a,b){for(var c=a.split("|"),d=a.length;d--;)s.attrHandle[c[d]]=b}function m(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||ka)-(~a.sourceIndex||ka);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function g(a){return function(b){return"input"===b.nodeName.toLowerCase()&&
b.type===a}}function k(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function l(a){return e(function(b){b=+b;return e(function(c,d){for(var e,f=a([],c.length,b),h=f.length;h--;)if(c[e=f[h]])c[e]=!(d[e]=c[e])})})}function t(a){return a&&typeof a.getElementsByTagName!==R&&a}function q(){}function n(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function w(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=ta++;return b.first?function(b,c,
f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,P){var A,h,m=[C,f];if(P)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,P))return!0}else for(;b=b[d];)if(1===b.nodeType||e){h=b[x]||(b[x]={});if((A=h[d])&&A[0]===C&&A[1]===f)return m[2]=A[2];h[d]=m;if(m[2]=a(b,c,P))return!0}}}function p(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function Z(a,b,c,d,e){for(var f,h=[],m=0,g=a.length,k=null!=b;m<g;m++)if(f=a[m])if(!c||c(f,d,e))h.push(f),
k&&b.push(m);return h}function ea(a,b,d,f,h,m){f&&!f[x]&&(f=ea(f));h&&!h[x]&&(h=ea(h,m));return e(function(e,m,g,k){var l,t,ia=[],D=[],n=m.length,q;if(!(q=e)){q=b||"*";for(var r=g.nodeType?[g]:g,s=[],I=0,w=r.length;I<w;I++)c(q,r[I],s);q=s}q=a&&(e||!b)?Z(q,ia,a,g,k):q;r=d?h||(e?a:n||f)?[]:m:q;d&&d(q,r,g,k);if(f){l=Z(r,D);f(l,[],g,k);for(g=l.length;g--;)if(t=l[g])r[D[g]]=!(q[D[g]]=t)}if(e){if(h||a){if(h){l=[];for(g=r.length;g--;)if(t=r[g])l.push(q[g]=t);h(null,r=[],l,k)}for(g=r.length;g--;)if((t=r[g])&&
-1<(l=h?N.call(e,t):ia[g]))e[l]=!(m[l]=t)}}else r=Z(r===m?r.splice(n,r.length):r),h?h(null,m,r,k):K.apply(m,r)})}function fa(a){var b,c,d,e=a.length,f=s.relative[a[0].type];c=f||s.relative[" "];for(var h=f?1:0,m=w(function(a){return a===b},c,!0),g=w(function(a){return-1<N.call(b,a)},c,!0),k=[function(a,c,d){return!f&&(d||c!==$)||((b=c).nodeType?m(a,c,d):g(a,c,d))}];h<e;h++)if(c=s.relative[a[h].type])k=[w(p(k),c)];else{c=s.filter[a[h].type].apply(null,a[h].matches);if(c[x]){for(d=++h;d<e&&!s.relative[a[d].type];d++);
return ea(1<h&&p(k),1<h&&n(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(Y,"$1"),c,h<d&&fa(a.slice(h,d)),d<e&&fa(a=a.slice(d)),d<e&&n(a))}k.push(c)}return p(k)}function ua(a,b){var d=0<b.length,f=0<a.length,h=function(e,h,m,g,k){var l,t,r,Q=0,q="0",D=e&&[],n=[],I=$,w=e||f&&s.find.TAG("*",k),v=C+=null==I?1:Math.random()||0.1,sa=w.length;for(k&&($=h!==y&&h);q!==sa&&null!=(l=w[q]);q++){if(f&&l){for(t=0;r=a[t++];)if(r(l,h,m)){g.push(l);break}k&&(C=v)}d&&((l=!r&&l)&&Q--,e&&D.push(l))}Q+=
q;if(d&&q!==Q){for(t=0;r=b[t++];)r(D,n,h,m);if(e){if(0<Q)for(;q--;)!D[q]&&!n[q]&&(n[q]=va.call(g));n=Z(n)}K.apply(g,n);k&&(!e&&0<n.length&&1<Q+b.length)&&c.uniqueSort(g)}k&&(C=v,$=I);return D};return d?e(h):h}var S,v,s,aa,la,V,ga,ja,$,L,T,J,y,F,E,z,O,ba,U,x="sizzle"+-new Date,B=a.document,C=0,ta=0,ma=b(),na=b(),oa=b(),ha=function(a,b){a===b&&(T=!0);return 0},R="undefined",ka=-2147483648,wa={}.hasOwnProperty,M=[],va=M.pop,xa=M.push,K=M.push,pa=M.slice,N=M.indexOf||function(a){for(var b=0,c=this.length;b<
c;b++)if(this[b]===a)return b;return-1},Y=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,ya=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,za=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Aa=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ba=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Ca=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ca={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Da=/^(?:input|select|textarea|button)$/i,Ea=/^h\d$/i,W=/^[^{]+\{\s*\[native \w/,qa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,ra=/'|\\/g,G=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,H=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{K.apply(M=pa.call(B.childNodes),B.childNodes),M[B.childNodes.length].nodeType}catch(Fa){K={apply:M.length?function(a,b){xa.apply(a,pa.call(b))}:function(a,b){for(var c=
a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}v=c.support={};la=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};J=c.setDocument=function(a){var b=a?a.ownerDocument||a:B;a=b.defaultView;if(b===y||9!==b.nodeType||!b.documentElement)return y;y=b;F=b.documentElement;E=!la(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){J()},!1):a.attachEvent&&a.attachEvent("onunload",function(){J()}));v.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});
v.getElementsByTagName=f(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=W.test(b.getElementsByClassName)&&f(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=f(function(a){F.appendChild(a).id=x;return!b.getElementsByName||!b.getElementsByName(x).length});v.getById?(s.find.ID=function(a,b){if(typeof b.getElementById!==R&&E){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},s.filter.ID=function(a){var b=a.replace(G,H);return function(a){return a.getAttribute("id")===b}}):(delete s.find.ID,s.filter.ID=function(a){var b=a.replace(G,H);return function(a){return(a=typeof a.getAttributeNode!==R&&a.getAttributeNode("id"))&&a.value===b}});s.find.TAG=v.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==R)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=
f[e++];)1===c.nodeType&&d.push(c);return d}return f};s.find.CLASS=v.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==R&&E)return b.getElementsByClassName(a)};O=[];z=[];if(v.qsa=W.test(b.querySelectorAll))f(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&z.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||z.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||z.push(":checked")}),f(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&z.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||z.push(":enabled",":disabled");a.querySelectorAll("*,:x");z.push(",.*:")});(v.matchesSelector=W.test(ba=F.matches||F.webkitMatchesSelector||F.mozMatchesSelector||F.oMatchesSelector||F.msMatchesSelector))&&
f(function(a){v.disconnectedMatch=ba.call(a,"div");ba.call(a,"[s!='']:x");O.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});z=z.length&&RegExp(z.join("|"));O=O.length&&RegExp(O.join("|"));
U=(a=W.test(F.compareDocumentPosition))||W.test(F.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ha=a?function(a,c){if(a===c)return T=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):
1;return d&1||!v.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===B&&U(B,a)?-1:c===b||c.ownerDocument===B&&U(B,c)?1:L?N.call(L,a)-N.call(L,c):0:d&4?-1:1}:function(a,c){if(a===c)return T=!0,0;var d,e=0;d=a.parentNode;var f=c.parentNode,X=[a],h=[c];if(!d||!f)return a===b?-1:c===b?1:d?-1:f?1:L?N.call(L,a)-N.call(L,c):0;if(d===f)return m(a,c);for(d=a;d=d.parentNode;)X.unshift(d);for(d=c;d=d.parentNode;)h.unshift(d);for(;X[e]===h[e];)e++;return e?m(X[e],h[e]):X[e]===B?-1:h[e]===
B?1:0};return b};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==y&&J(a);b=b.replace(Aa,"='$1']");if(v.matchesSelector&&E&&(!O||!O.test(b))&&(!z||!z.test(b)))try{var d=ba.call(a,b);if(d||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(e){}return 0<c(b,y,null,[a]).length};c.contains=function(a,b){(a.ownerDocument||a)!==y&&J(a);return U(a,b)};c.attr=function(a,b){(a.ownerDocument||a)!==y&&J(a);var c=s.attrHandle[b.toLowerCase()],
c=c&&wa.call(s.attrHandle,b.toLowerCase())?c(a,b,!E):void 0;return void 0!==c?c:v.attributes||!E?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var b,c=[],d=0,e=0;T=!v.detectDuplicates;L=!v.sortStable&&a.slice(0);a.sort(ha);if(T){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}L=null;return a};aa=c.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===
b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=aa(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=aa(b);return c};s=c.selectors={cacheLength:50,createPseudo:e,match:ca,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(G,H);a[3]=(a[3]||a[4]||a[5]||"").replace(G,H);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ca.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(c&&Ba.test(c)&&(b=V(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=
a.replace(G,H).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ma[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ma(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==R&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(e){e=c.attr(e,a);if(null==e)return"!="===b;if(!b)return!0;e+="";return"="===b?e===d:"!="===b?
e!==d:"^="===b?d&&0===e.indexOf(d):"*="===b?d&&-1<e.indexOf(d):"$="===b?d&&e.slice(-d.length)===d:"~="===b?-1<(" "+e+" ").indexOf(d):"|="===b?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),h="last"!==a.slice(-4),m="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,g){var k,l,t,A,q;c=f!==h?"nextSibling":"previousSibling";var r=b.parentNode,P=m&&b.nodeName.toLowerCase();g=!g&&!m;if(r){if(f){for(;c;){for(l=b;l=l[c];)if(m?l.nodeName.toLowerCase()===
P:1===l.nodeType)return!1;q=c="only"===a&&!q&&"nextSibling"}return!0}q=[h?r.firstChild:r.lastChild];if(h&&g){g=r[x]||(r[x]={});k=g[a]||[];A=k[0]===C&&k[1];t=k[0]===C&&k[2];for(l=A&&r.childNodes[A];l=++A&&l&&l[c]||(t=A=0)||q.pop();)if(1===l.nodeType&&++t&&l===b){g[a]=[C,A,t];break}}else if(g&&(k=(b[x]||(b[x]={}))[a])&&k[0]===C)t=k[1];else for(;l=++A&&l&&l[c]||(t=A=0)||q.pop();)if((m?l.nodeName.toLowerCase()===P:1===l.nodeType)&&++t)if(g&&((l[x]||(l[x]={}))[a]=[C,t]),l===b)break;t-=e;return t===d||
0===t%d&&0<=t/d}}},PSEUDO:function(a,b){var d,f=s.pseudos[a]||s.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return f[x]?f(b):1<f.length?(d=[a,a,"",b],s.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,c){for(var d,e=f(a,b),h=e.length;h--;)d=N.call(a,e[h]),a[d]=!(c[d]=e[h])}):function(a){return f(a,0,d)}):f}},pseudos:{not:e(function(a){var b=[],c=[],d=ga(a.replace(Y,"$1"));return d[x]?e(function(a,b,c,e){e=d(a,null,e,[]);for(var f=a.length;f--;)if(c=e[f])a[f]=!(b[f]=c)}):
function(a,e,f){b[0]=a;d(b,null,f,c);return!c.pop()}}),has:e(function(a){return function(b){return 0<c(a,b).length}}),contains:e(function(a){a=a.replace(G,H);return function(b){return-1<(b.textContent||b.innerText||aa(b)).indexOf(a)}}),lang:e(function(a){Ca.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(G,H).toLowerCase();return function(b){var c;do if(c=E?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===F},focus:function(a){return a===y.activeElement&&(!y.hasFocus||y.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!s.pseudos.empty(a)},header:function(a){return Ea.test(a.nodeName)},input:function(a){return Da.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:l(function(){return[0]}),
last:l(function(a,b){return[b-1]}),eq:l(function(a,b,c){return[0>c?c+b:c]}),even:l(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:l(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:l(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:l(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};s.pseudos.nth=s.pseudos.eq;for(S in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})s.pseudos[S]=g(S);for(S in{submit:!0,reset:!0})s.pseudos[S]=k(S);q.prototype=s.filters=
s.pseudos;s.setFilters=new q;V=c.tokenize=function(a,b){var d,e,f,h,g,m,k;if(g=na[a+" "])return b?0:g.slice(0);g=a;m=[];for(k=s.preFilter;g;){if(!d||(e=ya.exec(g)))e&&(g=g.slice(e[0].length)||g),m.push(f=[]);d=!1;if(e=za.exec(g))d=e.shift(),f.push({value:d,type:e[0].replace(Y," ")}),g=g.slice(d.length);for(h in s.filter)if((e=ca[h].exec(g))&&(!k[h]||(e=k[h](e))))d=e.shift(),f.push({value:d,type:h,matches:e}),g=g.slice(d.length);if(!d)break}return b?g.length:g?c.error(a):na(a,m).slice(0)};ga=c.compile=
function(a,b){var c,d=[],e=[],f=oa[a+" "];if(!f){b||(b=V(a));for(c=b.length;c--;)f=fa(b[c]),f[x]?d.push(f):e.push(f);f=oa(a,ua(e,d));f.selector=a}return f};ja=c.select=function(a,b,c,d){var e,f,h,g,m="function"===typeof a&&a,k=!d&&V(a=m.selector||a);c=c||[];if(1===k.length){f=k[0]=k[0].slice(0);if(2<f.length&&"ID"===(h=f[0]).type&&v.getById&&9===b.nodeType&&E&&s.relative[f[1].type]){if(b=(s.find.ID(h.matches[0].replace(G,H),b)||[])[0])m&&(b=b.parentNode);else return c;a=a.slice(f.shift().value.length)}for(e=
ca.needsContext.test(a)?0:f.length;e--;){h=f[e];if(s.relative[g=h.type])break;if(g=s.find[g])if(d=g(h.matches[0].replace(G,H),da.test(f[0].type)&&t(b.parentNode)||b)){f.splice(e,1);a=d.length&&n(f);if(!a)return K.apply(c,d),c;break}}}(m||ga(a,k))(d,b,!E,c,da.test(a)&&t(b.parentNode)||b);return c};v.sortStable=x.split("").sort(ha).join("")===x;v.detectDuplicates=!!T;J();v.sortDetached=f(function(a){return a.compareDocumentPosition(y.createElement("div"))&1});f(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||h("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!v.attributes||!f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&h("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||h("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof u&&u.amd?u(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.platforms=function(){var a={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},
ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id],section[id]",/^post(\d+)$/],scope:"td[id^='td_post_'] div[id^='post_message_'],td[id^='td_post_'] div[id^='post_message_'] ~ div:not([class]),div[id^='td_post_'] div[id^='post_message_']"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],
scope:null}};return function(c){return b.extend(a[c]||{},{getPostIDs:function(){var a=[],c=this.id_finder;c&&b.each(b.select(c[0]),function(b){var h=c[2]||"id";(b=b[h]?b[h].match(c[1]):null)&&a.push(b[1])});return a.length?a:null}})}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),
jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var k,n,p;g={PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",api:function(){var a=function(a,c,f){f=f||{};c=b.extend(g.commonParams(a),c);c.subId&&c.key!==k.key&&(c.subId=null);return{method:a,opts:f,params:c}},c=function(a){return b.request(k.api_url+"/"+a.method,a.params,a.opts)};return b.batchable({batch:function(){var d=function(a,c){a=b.fromJSON(a)||
{};b.each(a,function(a,d){var e,g=c[d];a&&g&&("domains"===d&&"array"===b.type(a)&&(a={results:a}),a="string"===b.type(a)&&(e=a.match(/^[^(]+\((.*)\);?\s*$/))?b.fromJSON("["+e[1]+"]")||{}:[a],g.apply(window,a))})};return function(e){var f={},h={};b.each(e,function(c){c=a.apply(this,c);h[c.method]=c.opts.fn||b.noop;f[c.method]=b.prune(c.params)});c({method:"batch",params:b.extend(g.commonParams(),{batch:window.JSON.stringify(f)}),opts:{jsonp:!1,fn:function(a){d(a,h)}}})}}(),single:function(b,e,f){b=
a(b,e,f);return c(b)}})}(),addEventListener:function(a,b){this.fire(a,b)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var f=a.open("",c);f.focus();return f}},c=function(a){var c=a.previousSibling,f=a.nextSibling,h=["",a.textContent,""],m=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},k=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g,
" ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==h[1]&&(h[0]=c&&3===c.nodeType?m(c,"previous"):"",h[2]=f&&3===f.nodeType?m(f,"next"):"",h=k.apply(this,h),""!==h[0]&&""!==h[2]&&(h[0]=h[0].split(" ").reverse().slice(0,10+(" "===h[0].substr(h[0].length-1,1)?1:0)).reverse().join(" "),h[2]=h[2].split(" ").slice(0,
10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:h[0],after:h[2],txt:h[1],loc:location.href,out:b.getActualHref(a),v:2},g.log("info",b.toQuery(a))))};return function(d,e){var f,h,g,l,n=b.context(d)||window;e=d.target||e;e=!e||e===n.name||"_top"===e&&n.top===n||"_parent"===e&&n.parent===n?"_self":e;g=a(n,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))l="go";else try{if(void 0===g.document)throw!0;l="jsonp"}catch(w){l="go"}f=b.destructing(b.bind(function(){k.time_click&&
arguments.length&&this.logTime("clk");var a=b.toArray(arguments);a.unshift(d,g,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||!k.enabled)return f();h=this.clickParams(d,l);this.logTime();k.log_context&&c(d);if("go"===l)this.redirect(this.api.now("click",h,{"return":!0}),n,g,e);else if(g===n)this.api.now("click",h,{fn:f,timeout:k.click_timeout});else{if(b.contextIsAncestor(n,g))return this.redirect(b.getActualHref(d),
n,g,e);f=b.exceptionLogger(f);setTimeout(function(){f()},k.click_timeout);g.document.open();g.callback=f;g.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",h,{fn:"callback","return":!0})+'">\x3c/script></head></html>');g.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:k.reaffiliate||null,title:window.document.title,txt:a.innerHTML});
128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:k.key?null:k.dr_key,key:k.key,libId:k.library_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:k.cuid,loc:location.href,subId:k.sub_id,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,b){function c(a,b){0==k||1E3<b?a(0==k&&g):setTimeout(function(){c(a,2*b)},2*b)}function h(){--k||(g=!l&&n)}var g=
!1,k=2,l=!1,n=!1;if("function"==typeof b){a+="?ch=*&rn=*";var t=11*Math.random(),q=new Image;q.onload=h;q.onerror=function(){l=!0;h()};q.src=a.replace(/\*/,1).replace(/\*/,t);q=new Image;q.onload=h;q.onerror=function(){n=!0;h()};q.src=a.replace(/\*/,2).replace(/\*/,t);c(b,250)}}}}catch(c){a={detect:function(a,b){b(!0)}}}return function(c){var e=b.updateUrl(k.asset_url,{pathname:"/images/pixel.gif"});a.detect(e,c)}}(),enabled:function(){if(k.enabled&&n!==window&&window.vglnk&&(window.vglnk.key||"function"===
typeof window.vglnk))k.enabled=!1;return k.enabled},expose:function(a,c){if(c=c||this[a])"function"===typeof c?c=b.exceptionLogger(b.bind(c,this)):"object"===typeof c&&(c=b.clone(c)),p[a]||(p[a]=c)},fire:function(){var a={};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,
c){if(k.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.exceptionLogger(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=b.cache(a,"href"),b.cache(a,"href",null)}},harmony:function(){b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return k.harmony_level<=a}}(),init:function(){var a=function(){var a=
!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var c=this;if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(d){}b.exceptionLogger(b.bind(c.logException,c),!k.dev);return b.exceptionLogger(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);p=n[l]=b.noop;this.expose("click");
this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return g.registerProcessor.apply(g,arguments)});b.extend(p,p===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),
this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.exceptionLogger(b.destructing(b.bind(function(){a=!0;k.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c={left:g.onClick,right:g.onContextmenu},d={left:b.noop,right:b.noop},e=b.traits.windowLevelHandlers?a:a.document,f=function(e){e=e||a.event;if((e=b.eventLink(e))&&!b.cache(e,"evented"))h(e,
g.harmony(b.harmony.LINK_LEVEL_EVENTS)?c:d),b.cache(e,"evented",!0)},h=function(a,c){b.on(a,"click",b.bind(c.left,g));b.on(a,"contextmenu",b.bind(c.right,g))};b.on(e,"copy",b.bind(g.onCopy,g));b.on(e,"mousedown",f);if(g.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",f)})});(!b.traits.quirksMode||g.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&h(e,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",
vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(p[b[a]]=window[a],"vglnk_domain"===a&&(p[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){k.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(g);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){b.each(b.toArray(a.document.links),b.bind(this.processLink,this))},
this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,b=l.split("."),d;for(l=b.pop();0<b.length;)d=b.shift(),a[d]=a[d]||{},a=a[d];n=a;p=n[l]=n[l]||{}},initOptions:function(){var a;this.initLegacyOptions();k=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,sub_id:null,reaffiliate:!1,
commercial:null,harmony_level:0,rewrite_modified:!1,rewrite_original:!0}),k,p,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in k)"_plugin"===a.substr(-7)&&delete k[a]},initPlugins:function(){var a,c=1,d={},e={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},
f=function(b){return function(b){return function(){delete d[b].opts.mode;c=1;clearTimeout(a);m()}}(b)},h=function(a){var c;b.find(e,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:k.key,link_phrases:!1});a[c].link_urls=k.link_urls;return a},m=function(){var e=!1,f={},h=function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);g.log.apply(this,c)}}};a=null;b.each(d,function(a,c){a.setup=a.setup||window.vglnk&&window.vglnk[c+"_plugin"];a.setup?(!a.run&&
"function"===b.type(a.setup)&&(a.run=a.setup(a.opts,b.clone(b),p,h(a.opts.key||k.key))||b.noop),a.opts.mode===g.PLUGIN_MANUAL?f[c]=a:a.run()):(e=!0,f[c]=a)});d=f;e&&(a=setTimeout(b.exceptionLogger(m),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},l=function(){setTimeout(function(){g.api.flush()},100);m();b.on("DOMReady",function(){setTimeout(g.api.flush,0)})};return function(a){a=h(a);b.each(a,b.bind(function(a,b){b=e[b]||b;"object"===typeof a&&!1!==a.enabled&&(d[b]={opts:a},a.mode===this.PLUGIN_MANUAL&&
this.expose("init_"+b,f(b)))},this));l()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(k.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){k.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&
(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["norewrite","noskim"],custom:function(c){var e,f="";try{e=c.hostname,f=c.protocol,e.charAt(0)}catch(h){return!0}""!==e&&(e=b.canonicalizeHostname(c));return""===e||a===e||"object"===b.type(k.commercial)&&!k.commercial[e]||!f.match(/^https?:$/i)||
k.norewrite[e]||!(k.rewrite_original||b.cache(c,"type"))}});return function(a){return c(a,{ancestors:!1})}}(),log:function(a,c,d,e){var f,h=b.toQuery({libId:k.library_id,nocache:b.uniqid()});f="pixel.gif";if("custom"===a)h+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(e)?e:[e],function(a){b.each(["e","i","o"],function(b){delete a[b]});h+="&"+b.toQuery(a)});else{h+="&"+b.toQuery({key:k.key,drKey:k.key?null:k.dr_key});if("time"===a)f="time.gif",a={time:d,type:c};else if("exception"===a)a={e:c,
o:d};else if("info"===a)a={i:c};else return;h+="&"+b.toQuery(a)}f=k.api_url+"/"+f+"?"+h;b.transmitsPII(f)||(b.createEl("img").src=f)},logException:function(a){if(k.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,c,d,
e,f){var h=e||b.getActualHref(a),g=b.bind(function(){this.redirect(h,b.context(a),c,d)},this);"object"===typeof f&&(f.tracking||f.image)?(e=b.createEl(f.tracking?"iframe":"img",{src:f.tracking||f.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(b.exceptionLogger(g),f.timeout||k.hop_timeout)):g()},onApiPing:function(a,c,d,e,f,h){k.rewrite_original=!1;f=b.reformatKeys(f||{});var m,l;e=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&
b.each(a,d);return c};l=b.extend(k.plugins,f.plugins);k=b.extend(k,f);delete k.plugins;k.library_id=a;k.click_timeout=c;k.time_ping&&this.logTime("png");"array"===b.type(k.testing_js)&&0<k.testing_js.length&&b.each(k.testing_js,function(a){b.jsonp(a)});b.extend(k.norewrite,e(d));b.extend(k.nofollow,e(h));for(m in k)"on"===m.toLowerCase().substr(0,2)&&(2<m.length&&"function"===b.type(k[m]))&&(b.on(g,m.toLowerCase().substr(2),b.bind(k[m],window)),delete k[m]);this.initPlugins(l);this.initContext(window);
this.fire("libready")},onClick:function(a){a=a||window.event;var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=b.eventLink(a);if(e&&this.isRewritable(e)&&!c&&d&&!b.isDefaultPrevented(a))return this.click(e),b.preventDefault(a)},onContextmenu:function(a){(a=b.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(a){var c,d,e,f=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{e=
d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(h){}0<e.length&&128>=e.length&&f.push(e)}}b.each(f,function(a){g.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(k[a]=b);return k[a]},ping:function(){var a=!1;return function(){if(!a&&(k.key||k.dr_key)){var c={ref:document.referrer||null};a=!0;b.transmitsPII(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&
(c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),processLink:function(a){if(this.isRewritable(a)){var c=b.cache(a,"processors")||{};b.each(this.registerProcessor(),function(b){c[b.id]||b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a}},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,e){c=c||window.top;!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):
b.traits.jsRedirectSetsReferrer?setTimeout(b.exceptionLogger(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,e),e.rel="norewrite",c.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},registerProcessor:function(){var a=!1,c=[],d=function(d){if(void 0===d)return c;"function"===b.type(d)&&(c.push({id:b.uniqid(),fn:d}),a&&this.initLinks())};d(function(){a=!0});return d}()};g.init();try{delete window.vglnk_self}catch(w){}})("undefined"===
typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(l,g,b){var u={},k;l=g.extend({any:!0},l);k={getDomains:function(){var l=[];g.each(u,function(b,g){l.push(g)});0<l.length&&b.api("domains",{domains:l.join("|")},{fn:g.bind(k.onDomainApi,k)})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,g.on("DOMReady",g.bind(this.getDomains,this)))}}(),onDomainApi:function(k){var l;"object"===g.type(k)&&"array"===g.type(k.results)&&(l={},g.each(k.results,function(b){l[b]=!0}),b.opt("commercial",l))},saveDomain:function(b){b=
g.canonicalizeHostname(b);u[b]=!0},setup:function(){b.opt("rewrite_original",!0);l.any||b.registerProcessor(function(b){k.initDomainLookup();k.saveDomain(b)})}};return function(){k.setup()}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,g,b){return function(){b.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(l,g){var b="https:"===document.location.protocol,u={setup:function(){window._comscore=window._comscore||[]},run:function(){var k=window._comscore;k&&"function"===g.type(k.push)&&(k.push({c1:8,c2:17570528,c3:1}),g.jsonp("//"+(b?"sb":"b")+".scorecardresearch.com/beacon.js"))}};u.setup();return function(){u.run()}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,g,b){l=g.extend({key:null},l);var u={init:function(){g.each(this.getDRSearchForms(),function(b){if(!g.cache(b,"evented")){var l=u.getInput(b),p=function(){l.value||g.css(l,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};g.cache(b,"evented",!0);b.onsubmit=null;l.onfocus=null;l.onblur=null;g.on(l,"focus",function(){g.css(l,{"background-image":"none"})});g.on(l,"blur",p);p();g.on(b,"submit",function(g){u.onSubmit(g,b)})}})},
getDRSearchForms:function(){var b=[];g.each(document.getElementsByTagName("form"),function(g){u.getInput(g)&&g.id.match(/^DR-ebay-search(CSS|2)?$/i)&&b.push(g)});return b},getInput:function(b){return b.p||b.q2},onSubmit:function(k,n){k=k||window.event;var p="http://shop.ebay.com/i.html?"+g.toQuery({_nkw:u.getInput(n).value}),p=g.createA(p,"_blank");g.cache(p,"params",{key:l.key});b.click(p);return g.preventDefault(k)}};return function(){l.key&&(u.init(),g.on("DOMReady",g.bind(u.init,u)))}};
window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(l,g,b,u){var k,n={},p=0;l=g.extend({platform:null},l);k={getLinks:function(){var n=g.platforms(l.platform).getPostIDs();b.api("optimize",{pt:l.platform,i:n?n.join("|"):null,u:location.href},{fn:g.bind(k.onOptimizeApi,k)})},log:function(){u("optimize",{ct:p})},onOptimizeApi:function(b){"object"===g.type(b)&&"object"===g.type(b.optLinks)&&(n=b.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(){var b=g.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],
custom:function(a,b){if(b)return Boolean(g.cache(a,"type"))}}),a=function(a){var b=a.href,e=a.textContent||a.innerText,f=function(){var b=g.canonicalizeHostname(a);return g.canonicalizeHostname(g.createEl("a",{href:e}))===b},h=function(){var b;return f()?(b=g.fromQuery(a.search),g.find(b,function(a){return a===e})):!1};return{exact:b===e||function(){var a=e.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+g.map(a,g.escapeRegExp).join(".+")+"$").test(b)}()||h(),partial:function(){var b=g.canonicalizeHostname(a);
return RegExp("\\b"+g.escapeRegExp(b)+"\\b","i").test(e)}()||-1!==e.indexOf(b)}};return function(c){var d,e=n[c.href];if(e&&b(c)){d=a(c);if(d.exact){d=e.frdLink||e.optLink;for(var f;f=c.firstChild;)c.removeChild(f);c.appendChild(document.createTextNode(d))}else if(d.partial)return;g.cache(c,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});c.href=e.optLink;p++}}}(),optimizeLinks:function(){var l={data:!1,timing:!1};return function(a){l=g.extend(l,a);l.timing&&(l.data&&n)&&(b.registerProcessor(g.bind(this.optimizeLink,
k)),setTimeout(function(){k.log()},0))}}(),setup:function(){if(!l.platform||"full"===l.platform)this.getLinks();else g.on("DOMReady",g.bind(this.getLinks,this))}};k.setup();return function(){g.on("DOMReady",function(){k.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(l,g,b){l=g.extend({level:null},l);return function(){var g=parseInt(l.level,10);isFinite(g)&&b.opt("harmony_level",g)}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(l,g,b,u){var k,n,p=null,w={},a,c=0,d=0,e=0;l=g.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},l);if(l.key)return k=g.platforms(l.platform),n={addPhrasesToMatcher:function(b){var c="";"regexp"===g.type(b)?c=b.source:"array"===g.type(b)&&(c="(?:^|[\\s\"'\\(])("+g.map(b,function(a){return g.escapeRegExp(a).split(" ").join("\\s+")}).join("|")+
")(?=\\s|\\W*$|\\W{2})");""!==c&&(a=RegExp(a?"(?:"+c+"|"+a.source+")":c,"i"))},focusLink:function(a){a.id||(a.id=g.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(){var a=k.getPostIDs();b.api("insert",g.extend(n.getPartnerParams(),{cat:l.cat,mode:l.mode,pt:l.platform,ps:l.product_source,i:a?a.join("|"):null,u:location.href,type:l.type}),{fn:g.bind(n.onInsertApi,n)})},getPartnerParams:function(){var a,c,d=b.opt("partner"),e={};for(a in d)break;if(a)for(c in d[a])e[a+
"_"+c]=d[a][c];return e},initLink:function(a,c,d){if(d=l.link_target||d)a.target=d;a.rel="nofollow";a.href||(a.href=c.url);g.cache(a,"params",{exp:p,key:l.key,mid:c.mid,type:c.type||null});g.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var b={data:l.link_phrases?!1:l.link_urls,timing:!1},h=function(a,b){var c;c=g.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";g.cache(c,"type","inserted");g.cache(c,"phrase",a);l.ui&&(c.title="Link added by VigLink");
n.initLink(c,b);return c},k=function(b,f){for(var k,m,r,p,u=function(a){var b;a=!a||!l.per_phrase||!a.count||a.count<l.per_phrase;b=!l.per_page||c<l.per_page;return a&&b},D=function(a,b){var c,d,e,f,h,k,m,r,n,q,p=function(b){n.parentNode.insertBefore(a,n);n.parentNode.removeChild(n);return b},t=function(a,b,c){a=g.extend({},a);a.x1-=c;a.y1-=c;a.x2+=c;a.y2+=c;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};n=g.createEl("span");a.parentNode.insertBefore(n,a);n.appendChild(a);q=g.geometry(n);if(l.proximity||
l.same_proximity)for(k in w)if((m=w[k].links)&&!(w[k]===b&&!l.same_proximity||w[k]!==b&&!l.proximity)){r=w[k]===b?Math.max(l.same_proximity,l.proximity):l.proximity;c=0;for(d=m.length;c<d;c++){h=m[c].segments;e=0;for(f=h.length;e<f;e++)if(t(h[e].geometry,q,r))return p(!1)}}return p(!0)},I=function(a,b){var c,d,e,f,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===f||e.offsetTop===f.offsetTop?l.els.push(e):(h.segments.push(l),l={els:[e]}),f=
e;l.geometry=g.geometry.apply(g,l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};b&&b.data&&(Boolean(r=b.data.match(/^\s+/))||Boolean(r=b.data.match(a)));)m=r[0],p=r.slice(1).join(""),k=w[n.normalizePhrase(p)],m=b.data.indexOf(m)+m.length-p.length,0<m&&(b=b.splitText(m)),m=b.length<=p.length?null:b.splitText(p.length),p&&!k&&(k={url:p.match(/^https?:\/\//i)?p:"http://"+p,type:"U"}),k&&(k.url.match(/https?:\/\//i)&&p&&u(k)&&D(b,k))&&(p=h(p,k),g.cache(p,"unlinked")||("L"===k.type.toUpperCase()?
d++:e++,f(p,b),I(p,k),k.count++,c++)),b=m},r=function(b){var c=!1,d=b.parentNode,e=function(a,b){d.insertBefore(a,b);d.removeChild(b)};b.data&&(c=a.test(b.data.replace(/\s+/," ")));c&&k(b,e)},p=g.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return g.matches(a,"a[href]")}}),u=function(a){var b;if(a){if(p(a,{ancestors:!1,self:!0}))for(b=
a.firstChild;b;)a=b.nextSibling,1===b.nodeType?u(b):3===b.nodeType&&r(b),b=a}else g.each(g.select(l.scope),function(a){p(a,{ancestors:!0,self:!1})&&u(a)})};return function(c){b=g.extend(b,c);b.timing&&(b.data&&a)&&(u(),l.link_phrases&&n.log())}}(),loadPhrases:function(a){var b,c,d,e=[];b=0;for(c=a.length;b<c;b++)d=a[b],d.phrase&&d.url&&(d.phrase=this.normalizePhrase(d.phrase),w[d.phrase]||(e.push(d.phrase),w[d.phrase]={count:w[d.phrase]?w[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||
""}));0<e.length&&this.addPhrasesToMatcher(e);this.insertLinks({data:!0})},log:function(){var a,b,g={heavy:[],lite:[]},k=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(a in w)b=parseInt(w[a].count,10),0<b&&(b=[b,a.replace(/\|/g,"%7C")].join(),g["L"===w[a].type.toUpperCase()?"lite":"heavy"].push(b));g.lite.sort(k);g.heavy.sort(k);u("insert",[{ct:c,cl:d,ch:e,cu:0,exp:p},{pl:g.lite.join("|")},{ph:g.heavy.join("|")}])},onInsertApi:function(a){"object"===g.type(a)&&(p=a.exp,a.results&&this.loadPhrases(a.results))},
normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},setup:function(){l.scope=l.scope||k.scope||"body";l.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(l.link_phrases)if(!l.platform||"full"===l.platform)this.getPhrases();else g.on("DOMReady",g.bind(this.getPhrases,this))}},n.setup(),function(){g.on("DOMReady",function(){n.insertLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.spotlight_plugin=function(l,g,b){window.vglnk.spotlight_plugin.exports={$:g,opts:l,vglnk:b};return function(){(!g.browser.ie||6<g.browser.version)&&g.jsonp(b.opt("asset_url")+"/spotlight.js")}};
